### ISSUE TITLE
refactor : 어드민, 마이페이지

### ISSUE THREAD

**Issue by dle234** [JNU-econovation/jnu-wiki-fe#128]
## Description
리팩토링

## Todo
- [ ] alert -> toast 
- [ ] alert 파일 분리
- [ ] output 로직 상수로
- [ ] 경로 전부 절대경로로
- [ ] 중복되는 코드 합치기

## ETC
기타사항
