### ISSUE TITLE
refactor: 문서 상세 조회 리팩토링

### ISSUE THREAD

**Issue by baegyeong** [JNU-econovation/jnu-wiki-fe#132]
## Description
문서 상세 조회 코드 리팩토링

## Todo
- [x] `react-hook-form` 적용
- [x] 기본정보/내용 컴포넌트 분리
- [x] 기본정보에 도움말 추가
- [x] 기본정보 편집 후 저장/취소 시 지도엔 원래장소 마커만 남기기 (사용자가 클릭했던 마커도 같이 남아있는 이슈)
- [x] 코드 구조 리팩토링
