### ISSUE TITLE
style : 마이페이지 하단바, 로그인 회원가입 반응형 구현

### ISSUE THREAD

**Issue by dle234** [JNU-econovation/jnu-wiki-fe#141]
## Description
반응형 구현

## Todo
- [x] 마이페이지 하단 바 수정하기
- [x] 로그인 페이지 반응형 적용
- [x] 회원가입 페이지 반응형 적용

## ETC
기타사항
