### ISSUE TITLE
style: 디자인 변경

### ISSUE THREAD

**Issue by baegyeong** [JNU-econovation/jnu-wiki-fe#168]
## Description
자잘한 디자인을 수정한다.

## Todo
- [x] 모바일 화면시 검색바 위치 변경
- [x] 사이드바 없애기
- [x] 게시글 등록 버튼 제작
- [ ] 카테고리별 마커 색 변경
- [x] 이 지역 검색 버튼 위치 변경
- [x] 전대위키 로고 크기 변경
