### ISSUE TITLE
feat: 목록 조회

### ISSUE THREAD

**Issue by baegyeong** [JNU-econovation/jnu-wiki-fe#34]
## Description
viewpost를 클릭하면 문서 목록을 띄운다.
문서 목록에는 각 문서들의 정보가 담겨있다.

## Todo
- [x] viewPost 탭을 누르면 get 요청을 보낸다.
- [x] 목록 컴포넌트 안에 아이템 컴포넌트를 띄운다.
- [x] 아이템 컨포넌트에는 문서의 제목, 카테고리를 띄운다.
- [x] 위치에 따른 마커를 지도에 표시해둔다.
