### ISSUE TITLE
feat: 문서 창 접는 기능

### ISSUE THREAD

**Issue by baegyeong** [JNU-econovation/jnu-wiki-fe#79]
## Description
문서 목록 볼 때, 개별 문서 볼 때 문서를 사이드바 쪽으로 접을 수 있는 기능을 추가한다.

## Todo
- [x] 문서 센터-오른쪽 끝에 접는 버튼을 추가한다.
- [ ] 접는 버튼 클릭 시 문서창이 접힌다.
- [ ] 다시 버튼 클릭 시 문서창을 열 수 있어야 한다.

## ETC
